require("ts-node/register/type-check");
// require("./examples/apollo-engine/index.ts");
// require("./examples/authorization/index.ts");
// require("./examples/automatic-validation/index.ts");
// require("./examples/enums-and-unions/index.ts");
// require("./examples/interfaces-inheritance/index.ts");
// require("./examples/middlewares/index.ts");
// require("./examples/redis-subscriptions/index.ts");
// require("./examples/simple-subscriptions/index.ts");
// require("./examples/simple-usage/index.ts");
// require("./examples/using-container/index.ts");
// require("./examples/typeorm-basic-usage/index.ts");
// require("./examples/typeorm-lazy-relations/index.ts");
