subscription AllNotifications {
  normalSubscription {
    id
    message
    date
  }
}

subscription EvenNotifications {
  subscriptionWithFilter {
    id
    message
    date
  }
}

mutation {
  pubSubMutation(message: "Hello")
}

mutation {
  pubSubMutationToDynamicTopic(topic:"FOO_MESSAGES", message: "Hi Foo!")
}

subscription {
  subscriptionWithFilterToDyamicTopic (topic: "FOO_MESSAGES"){
    id, message
  }
}
