query GetPublicRecipes {
  recipes {
    title
    description
    averageRating
  }
}

query GetRecipesForAuthedUser {
  recipes {
    title
    description
    ingredients
    averageRating
  }
}

query GetRecipesForAdmin {
  recipes {
    title
    description
    ingredients
    averageRating
    ratings
  }
}

mutation AddRecipeByAuthedUser {
  addRecipe(title: "Sample Recipe") {
    averageRating
  }
}

mutation DeleteRecipeByAdmin {
  deleteRecipe(title: "Recipe 1")
}
