query GetRecipes {
  recipes {
    id
    title
    description
    creationDate
  }
}

query GetRecipesWithAuthor {
  recipes {
    id
    title
    author {
      id
      name
      email
      age
    }
  }
}

query GetUsers {
  users {
    id
    name
    email
    age
  }
}

query GetUsersWithRecipes {
  users {
    id
    name
    recipes {
      title
      description
      creationDate
    }
  }
}
