query GetRecipes {
  recipes {
    title
    description
    creationDate
  }
}

mutation CorrectAddRecipe {
  addRecipe(input: {
    title: "Correct title"
    description: "Very very very very very very very very long description"
  }) {
    creationDate
  }
}

mutation AddRecipeWithoutDesc {
  addRecipe(input: {
    title: "Correct title"
  }) {
    creationDate
  }
}

mutation IncorrectAddRecipe {
  addRecipe(input: {
    title: "Correct title"
    description: "Too short description"
  }) {
    creationDate
  }
}
