name: sponsor

on:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Dependencies
        run: |
          npm ci

      - name: Update images/sponsors.svg
        run: npm run sponsor
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSOR_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: MichalLytek
          SPONSORKIT_OPENCOLLECTIVE_KEY: ${{ secrets.SPONSOR_OPENCOLLECTIVE_TOKEN }}
          SPONSORKIT_OPENCOLLECTIVE_ID: "TODO: UPDATE_ME"
          SPONSORKIT_OPENCOLLECTIVE_TYPE: collective

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update sponsors image"
          add: "images/sponsors.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
